import numpy as np

# Define membership functions for y_position
def getMembershipYPos(y):
    degree = {
        "A": 0,
        "B": 0,
        "C": 0,
        "D": 0,
        "E": 0,
        "F": 0,
        "G": 0,
        "H": 0,
        "I": 0,
        "J": 0
    }
    
    if y < 25:
        degree["A"] = 1
    elif 25 <= y < 75:
        degree["A"] = float((75 - y) * (1 / 50))
        degree["B"] = float((y-25) * (1 / 50))
    elif 75 <= y < 125:
        degree["B"] = float((125 - y) * (1 / 50))
        degree["C"] = float((y-75) * (1 / 50))
    elif 125 <= y < 175:
        degree["C"] = float((175 - y) * (1 / 50))
        degree["D"] = float((y-125) * (1 / 50))
    elif 175 <= y < 225:
        degree["D"] = float((225 - y) * (1 / 50))
        degree["E"] = float((y-175) * (1 / 50))
    elif 225 <= y < 275:
        degree["E"] = float((275 - y) * (1 / 50))
        degree["F"] = float((y-225) * (1 / 50))
    elif 275 <= y < 325:
        degree["F"] = float((325 - y) * (1 / 50))
        degree["G"] = float((y-275) * (1 / 50))
    elif 325 <= y < 375:
        degree["G"] = float((375 - y) * (1 / 50))
        degree["H"] = float((y-325) * (1 / 50))
    elif 375 <= y < 425:
        degree["H"] = float((425 - y) * (1 / 50))
        degree["I"] = float((y-375) * (1 / 50))
    elif 425 <= y < 475:
        degree["I"] = float((475 - y) * (1 / 50))
        degree["J"] = float((y-425) * (1 / 50))
    elif y >= 475:
        degree["J"] = 1
    
    return degree

# Define fuzzy membership functions for y_speed
def getMembershipYSpeed(speed):
    degree = {
        "a": 0,
        "b": 0,
        "c": 0,
        "d": 0,
        "e": 0,
        "f": 0,
        "g": 0,
        "h": 0,
        "i": 0,
        "j": 0
    }
    
    if speed < -7:
        degree["a"] = 1
    elif -7 <= speed < -5:
        degree["a"] = float((-5 - speed) * (1 / 2))
        degree["b"] = float((speed + 7) * (1 / 2))
    elif -5 <= speed < -3:
        degree["b"] = float((-3 - speed) * (1 / 2))
        degree["c"] = float((speed+5) * (1 / 2))
    elif -3 <= speed < -1:
        degree["c"] = float((-1 - speed) * (1 / 2))
        degree["d"] = float((speed+3) * (1 / 2))
    elif -1 <= speed < 0:
        degree["d"] = float((0 - speed) * (1 / 2))
        degree["e"] = float((speed+1) * (1 / 2))
    elif 0 <= speed < 1:
        degree["e"] = float((1 - speed) * (1 / 2))
        degree["f"] = float((speed-0) * (1 / 2))
    elif 1 <= speed < 3:
        degree["f"] = float((3 - speed) * (1 / 2))
        degree["g"] = float((speed-1) * (1 / 2))
    elif 3 <= speed < 5:
        degree["g"] = float((5 - speed) * (1 / 2))
        degree["h"] = float((speed-3) * (1 / 2))
    elif 5 <= speed < 7:
        degree["h"] = float((7 - speed) * (1 / 2))
        degree["i"] = float((speed-5) * (1 / 2))
    elif speed >= 7:
        degree["i"] = 1
    
    return degree

# Define fuzzy membership functions for x_dist
def getMembershipXDist(pos):
    degree = {
        "a": 0,
        "b": 0,
        "c": 0,
        "d": 0,
        "e": 0,
        "f": 0       
    }
    if pos < 50:
        degree["a"] = 1
    elif 50 <= pos < 150:
        degree["a"] = float((150 - pos) * (1 / 100))
        degree["b"] = float((pos - 50) * (1 / 100))
    elif 150 <= pos < 250:
        degree["b"] = float((250- pos) * (1 / 100))
        degree["c"] = float((pos-150) * (1 / 100))
    elif 250 <= pos < 350:
        degree["c"] = float((350 - pos) * (1 / 100))
        degree["d"] = float((pos-250) * (1 / 100))
    elif 350 <= pos < 450:
        degree["d"] = float((450 - pos) * (1 / 100))
        degree["e"] = float((pos-350) * (1 / 100))
    elif 450 <= pos < 550:
        degree["e"] = float((550 - pos) * (1 / 100))
        degree["f"] = float((pos-450) * (1 / 100))
    elif pos >= 550:
        degree["f"] = 1
    
    return degree



# Define fuzzy rules 
def fuzzyInference(y, speed,pos):
    y_mem = getMembershipYPos(y)
    speed_mem = getMembershipYSpeed(speed)
    dist_mem=getMembershipXDist(pos)

    rule0=min(y_mem["B"], speed_mem["a"],dist_mem["f"])
    rule1=min(y_mem["B"], speed_mem["a"],dist_mem["f"])
    rule2=min(y_mem["B"], speed_mem["a"],dist_mem["e"])
    rule3=min(y_mem["B"], speed_mem["a"],dist_mem["d"])
    rule4=min(y_mem["B"], speed_mem["a"],dist_mem["c"])
    rule5=min(y_mem["B"], speed_mem["a"],dist_mem["b"])
    rule6=min(y_mem["B"], speed_mem["a"],dist_mem["a"])
    rule7=min(y_mem["B"], speed_mem["b"],dist_mem["f"])
    rule8=min(y_mem["B"], speed_mem["b"],dist_mem["f"])
    rule9=min(y_mem["B"], speed_mem["b"],dist_mem["e"])
    rule10=min(y_mem["B"], speed_mem["b"],dist_mem["d"])
    rule11=min(y_mem["B"], speed_mem["b"],dist_mem["c"])
    rule12=min(y_mem["B"], speed_mem["b"],dist_mem["b"])
    rule13=min(y_mem["B"], speed_mem["b"],dist_mem["a"])
    rule14=min(y_mem["B"], speed_mem["c"],dist_mem["f"])
    rule15=min(y_mem["B"], speed_mem["c"],dist_mem["f"])
    rule16=min(y_mem["B"], speed_mem["c"],dist_mem["e"])
    rule17=min(y_mem["B"], speed_mem["c"],dist_mem["d"])
    rule18=min(y_mem["B"], speed_mem["c"],dist_mem["c"])
    rule19=min(y_mem["B"], speed_mem["c"],dist_mem["b"])
    rule20=min(y_mem["B"], speed_mem["c"],dist_mem["a"])
    rule21=min(y_mem["B"], speed_mem["d"],dist_mem["f"])
    rule22=min(y_mem["B"], speed_mem["d"],dist_mem["f"])
    rule23=min(y_mem["B"], speed_mem["d"],dist_mem["e"])
    rule24=min(y_mem["B"], speed_mem["d"],dist_mem["d"])
    rule25=min(y_mem["B"], speed_mem["d"],dist_mem["c"])
    rule26=min(y_mem["B"], speed_mem["d"],dist_mem["b"])
    rule27=min(y_mem["B"], speed_mem["d"],dist_mem["a"])
    rule28=min(y_mem["B"], speed_mem["e"],dist_mem["f"])
    rule29=min(y_mem["B"], speed_mem["e"],dist_mem["f"])
    rule30=min(y_mem["B"], speed_mem["e"],dist_mem["e"])
    rule31=min(y_mem["B"], speed_mem["e"],dist_mem["d"])
    rule32=min(y_mem["B"], speed_mem["e"],dist_mem["c"])
    rule33=min(y_mem["B"], speed_mem["e"],dist_mem["b"])
    rule34=min(y_mem["B"], speed_mem["e"],dist_mem["a"])
    rule35=min(y_mem["B"], speed_mem["e"],dist_mem["f"])
    rule36=min(y_mem["B"], speed_mem["e"],dist_mem["f"])
    rule37=min(y_mem["B"], speed_mem["e"],dist_mem["e"])
    rule38=min(y_mem["B"], speed_mem["e"],dist_mem["d"])
    rule39=min(y_mem["B"], speed_mem["e"],dist_mem["c"])
    rule40=min(y_mem["B"], speed_mem["e"],dist_mem["b"])
    rule41=min(y_mem["B"], speed_mem["e"],dist_mem["a"])
    rule42=min(y_mem["B"], speed_mem["g"],dist_mem["f"])
    rule43=min(y_mem["B"], speed_mem["g"],dist_mem["f"])
    rule44=min(y_mem["B"], speed_mem["g"],dist_mem["e"])
    rule45=min(y_mem["B"], speed_mem["g"],dist_mem["d"])
    rule46=min(y_mem["B"], speed_mem["g"],dist_mem["c"])
    rule47=min(y_mem["B"], speed_mem["g"],dist_mem["b"])
    rule48=min(y_mem["B"], speed_mem["g"],dist_mem["a"])
    rule49=min(y_mem["B"], speed_mem["h"],dist_mem["f"])
    rule50=min(y_mem["B"], speed_mem["h"],dist_mem["f"])
    rule51=min(y_mem["B"], speed_mem["h"],dist_mem["e"])
    rule52=min(y_mem["B"], speed_mem["h"],dist_mem["d"])
    rule53=min(y_mem["B"], speed_mem["h"],dist_mem["c"])
    rule54=min(y_mem["B"], speed_mem["h"],dist_mem["b"])
    rule55=min(y_mem["B"], speed_mem["h"],dist_mem["a"])
    rule56=min(y_mem["B"], speed_mem["i"],dist_mem["f"])
    rule57=min(y_mem["B"], speed_mem["i"],dist_mem["f"])
    rule58=min(y_mem["B"], speed_mem["i"],dist_mem["e"])
    rule59=min(y_mem["B"], speed_mem["i"],dist_mem["d"])
    rule60=min(y_mem["B"], speed_mem["i"],dist_mem["c"])
    rule61=min(y_mem["B"], speed_mem["i"],dist_mem["b"])
    rule62=min(y_mem["B"], speed_mem["i"],dist_mem["a"])
    rule63=min(y_mem["B"], speed_mem["i"],dist_mem["f"])
    rule64=min(y_mem["B"], speed_mem["i"],dist_mem["f"])
    rule65=min(y_mem["B"], speed_mem["i"],dist_mem["e"])
    rule66=min(y_mem["B"], speed_mem["i"],dist_mem["d"])
    rule67=min(y_mem["B"], speed_mem["i"],dist_mem["c"])
    rule68=min(y_mem["B"], speed_mem["i"],dist_mem["b"])
    rule69=min(y_mem["B"], speed_mem["i"],dist_mem["a"])
    rule70=min(y_mem["C"], speed_mem["a"],dist_mem["f"])
    rule71=min(y_mem["C"], speed_mem["a"],dist_mem["f"])
    rule72=min(y_mem["C"], speed_mem["a"],dist_mem["e"])
    rule73=min(y_mem["C"], speed_mem["a"],dist_mem["d"])
    rule74=min(y_mem["C"], speed_mem["a"],dist_mem["c"])
    rule75=min(y_mem["C"], speed_mem["a"],dist_mem["b"])
    rule76=min(y_mem["C"], speed_mem["a"],dist_mem["a"])
    rule77=min(y_mem["C"], speed_mem["b"],dist_mem["f"])
    rule78=min(y_mem["C"], speed_mem["b"],dist_mem["f"])
    rule79=min(y_mem["C"], speed_mem["b"],dist_mem["e"])
    rule80=min(y_mem["C"], speed_mem["b"],dist_mem["d"])
    rule81=min(y_mem["C"], speed_mem["b"],dist_mem["c"])
    rule82=min(y_mem["C"], speed_mem["b"],dist_mem["b"])
    rule83=min(y_mem["C"], speed_mem["b"],dist_mem["a"])
    rule84=min(y_mem["C"], speed_mem["c"],dist_mem["f"])
    rule85=min(y_mem["C"], speed_mem["c"],dist_mem["f"])
    rule86=min(y_mem["C"], speed_mem["c"],dist_mem["e"])
    rule87=min(y_mem["C"], speed_mem["c"],dist_mem["d"])
    rule88=min(y_mem["C"], speed_mem["c"],dist_mem["c"])
    rule89=min(y_mem["C"], speed_mem["c"],dist_mem["b"])
    rule90=min(y_mem["C"], speed_mem["c"],dist_mem["a"])
    rule91=min(y_mem["C"], speed_mem["d"],dist_mem["f"])
    rule92=min(y_mem["C"], speed_mem["d"],dist_mem["f"])
    rule93=min(y_mem["C"], speed_mem["d"],dist_mem["e"])
    rule94=min(y_mem["C"], speed_mem["d"],dist_mem["d"])
    rule95=min(y_mem["C"], speed_mem["d"],dist_mem["c"])
    rule96=min(y_mem["C"], speed_mem["d"],dist_mem["b"])
    rule97=min(y_mem["C"], speed_mem["d"],dist_mem["a"])
    rule98=min(y_mem["C"], speed_mem["e"],dist_mem["f"])
    rule99=min(y_mem["C"], speed_mem["e"],dist_mem["f"])
    rule100=min(y_mem["C"], speed_mem["e"],dist_mem["e"])
    rule101=min(y_mem["C"], speed_mem["e"],dist_mem["d"])
    rule102=min(y_mem["C"], speed_mem["e"],dist_mem["c"])
    rule103=min(y_mem["C"], speed_mem["e"],dist_mem["b"])
    rule104=min(y_mem["C"], speed_mem["e"],dist_mem["a"])
    rule105=min(y_mem["C"], speed_mem["e"],dist_mem["f"])
    rule106=min(y_mem["C"], speed_mem["e"],dist_mem["f"])
    rule107=min(y_mem["C"], speed_mem["e"],dist_mem["e"])
    rule108=min(y_mem["C"], speed_mem["e"],dist_mem["d"])
    rule109=min(y_mem["C"], speed_mem["e"],dist_mem["c"])
    rule110=min(y_mem["C"], speed_mem["e"],dist_mem["b"])
    rule111=min(y_mem["C"], speed_mem["e"],dist_mem["a"])
    rule112=min(y_mem["C"], speed_mem["g"],dist_mem["f"])
    rule113=min(y_mem["C"], speed_mem["g"],dist_mem["f"])
    rule114=min(y_mem["C"], speed_mem["g"],dist_mem["e"])
    rule115=min(y_mem["C"], speed_mem["g"],dist_mem["d"])
    rule116=min(y_mem["C"], speed_mem["g"],dist_mem["c"])
    rule117=min(y_mem["C"], speed_mem["g"],dist_mem["b"])
    rule118=min(y_mem["C"], speed_mem["g"],dist_mem["a"])
    rule119=min(y_mem["C"], speed_mem["h"],dist_mem["f"])
    rule120=min(y_mem["C"], speed_mem["h"],dist_mem["f"])
    rule121=min(y_mem["C"], speed_mem["h"],dist_mem["e"])
    rule122=min(y_mem["C"], speed_mem["h"],dist_mem["d"])
    rule123=min(y_mem["C"], speed_mem["h"],dist_mem["c"])
    rule124=min(y_mem["C"], speed_mem["h"],dist_mem["b"])
    rule125=min(y_mem["C"], speed_mem["h"],dist_mem["a"])
    rule126=min(y_mem["C"], speed_mem["i"],dist_mem["f"])
    rule127=min(y_mem["C"], speed_mem["i"],dist_mem["f"])
    rule128=min(y_mem["C"], speed_mem["i"],dist_mem["e"])
    rule129=min(y_mem["C"], speed_mem["i"],dist_mem["d"])
    rule130=min(y_mem["C"], speed_mem["i"],dist_mem["c"])
    rule131=min(y_mem["C"], speed_mem["i"],dist_mem["b"])
    rule132=min(y_mem["C"], speed_mem["i"],dist_mem["a"])
    rule133=min(y_mem["C"], speed_mem["i"],dist_mem["f"])
    rule134=min(y_mem["C"], speed_mem["i"],dist_mem["f"])
    rule135=min(y_mem["C"], speed_mem["i"],dist_mem["e"])
    rule136=min(y_mem["C"], speed_mem["i"],dist_mem["d"])
    rule137=min(y_mem["C"], speed_mem["i"],dist_mem["c"])
    rule138=min(y_mem["C"], speed_mem["i"],dist_mem["b"])
    rule139=min(y_mem["C"], speed_mem["i"],dist_mem["a"])
    rule140=min(y_mem["D"], speed_mem["a"],dist_mem["f"])
    rule141=min(y_mem["D"], speed_mem["a"],dist_mem["f"])
    rule142=min(y_mem["D"], speed_mem["a"],dist_mem["e"])
    rule143=min(y_mem["D"], speed_mem["a"],dist_mem["d"])
    rule144=min(y_mem["D"], speed_mem["a"],dist_mem["c"])
    rule145=min(y_mem["D"], speed_mem["a"],dist_mem["b"])
    rule146=min(y_mem["D"], speed_mem["a"],dist_mem["a"])
    rule147=min(y_mem["D"], speed_mem["b"],dist_mem["f"])
    rule148=min(y_mem["D"], speed_mem["b"],dist_mem["f"])
    rule149=min(y_mem["D"], speed_mem["b"],dist_mem["e"])
    rule150=min(y_mem["D"], speed_mem["b"],dist_mem["d"])
    rule151=min(y_mem["D"], speed_mem["b"],dist_mem["c"])
    rule152=min(y_mem["D"], speed_mem["b"],dist_mem["b"])
    rule153=min(y_mem["D"], speed_mem["b"],dist_mem["a"])
    rule154=min(y_mem["D"], speed_mem["c"],dist_mem["f"])
    rule155=min(y_mem["D"], speed_mem["c"],dist_mem["f"])
    rule156=min(y_mem["D"], speed_mem["c"],dist_mem["e"])
    rule157=min(y_mem["D"], speed_mem["c"],dist_mem["d"])
    rule158=min(y_mem["D"], speed_mem["c"],dist_mem["c"])
    rule159=min(y_mem["D"], speed_mem["c"],dist_mem["b"])
    rule160=min(y_mem["D"], speed_mem["c"],dist_mem["a"])
    rule161=min(y_mem["D"], speed_mem["d"],dist_mem["f"])
    rule162=min(y_mem["D"], speed_mem["d"],dist_mem["f"])
    rule163=min(y_mem["D"], speed_mem["d"],dist_mem["e"])
    rule164=min(y_mem["D"], speed_mem["d"],dist_mem["d"])
    rule165=min(y_mem["D"], speed_mem["d"],dist_mem["c"])
    rule166=min(y_mem["D"], speed_mem["d"],dist_mem["b"])
    rule167=min(y_mem["D"], speed_mem["d"],dist_mem["a"])
    rule168=min(y_mem["D"], speed_mem["e"],dist_mem["f"])
    rule169=min(y_mem["D"], speed_mem["e"],dist_mem["f"])
    rule170=min(y_mem["D"], speed_mem["e"],dist_mem["e"])
    rule171=min(y_mem["D"], speed_mem["e"],dist_mem["d"])
    rule172=min(y_mem["D"], speed_mem["e"],dist_mem["c"])
    rule173=min(y_mem["D"], speed_mem["e"],dist_mem["b"])
    rule174=min(y_mem["D"], speed_mem["e"],dist_mem["a"])
    rule175=min(y_mem["D"], speed_mem["e"],dist_mem["f"])
    rule176=min(y_mem["D"], speed_mem["e"],dist_mem["f"])
    rule177=min(y_mem["D"], speed_mem["e"],dist_mem["e"])
    rule178=min(y_mem["D"], speed_mem["e"],dist_mem["d"])
    rule179=min(y_mem["D"], speed_mem["e"],dist_mem["c"])
    rule180=min(y_mem["D"], speed_mem["e"],dist_mem["b"])
    rule181=min(y_mem["D"], speed_mem["e"],dist_mem["a"])
    rule182=min(y_mem["D"], speed_mem["g"],dist_mem["f"])
    rule183=min(y_mem["D"], speed_mem["g"],dist_mem["f"])
    rule184=min(y_mem["D"], speed_mem["g"],dist_mem["e"])
    rule185=min(y_mem["D"], speed_mem["g"],dist_mem["d"])
    rule186=min(y_mem["D"], speed_mem["g"],dist_mem["c"])
    rule187=min(y_mem["D"], speed_mem["g"],dist_mem["b"])
    rule188=min(y_mem["D"], speed_mem["g"],dist_mem["a"])
    rule189=min(y_mem["D"], speed_mem["h"],dist_mem["f"])
    rule190=min(y_mem["D"], speed_mem["h"],dist_mem["f"])
    rule191=min(y_mem["D"], speed_mem["h"],dist_mem["e"])
    rule192=min(y_mem["D"], speed_mem["h"],dist_mem["d"])
    rule193=min(y_mem["D"], speed_mem["h"],dist_mem["c"])
    rule194=min(y_mem["D"], speed_mem["h"],dist_mem["b"])
    rule195=min(y_mem["D"], speed_mem["h"],dist_mem["a"])
    rule196=min(y_mem["D"], speed_mem["i"],dist_mem["f"])
    rule197=min(y_mem["D"], speed_mem["i"],dist_mem["f"])
    rule198=min(y_mem["D"], speed_mem["i"],dist_mem["e"])
    rule199=min(y_mem["D"], speed_mem["i"],dist_mem["d"])
    rule200=min(y_mem["D"], speed_mem["i"],dist_mem["c"])
    rule201=min(y_mem["D"], speed_mem["i"],dist_mem["b"])
    rule202=min(y_mem["D"], speed_mem["i"],dist_mem["a"])
    rule203=min(y_mem["D"], speed_mem["i"],dist_mem["f"])
    rule204=min(y_mem["D"], speed_mem["i"],dist_mem["f"])
    rule205=min(y_mem["D"], speed_mem["i"],dist_mem["e"])
    rule206=min(y_mem["D"], speed_mem["i"],dist_mem["d"])
    rule207=min(y_mem["D"], speed_mem["i"],dist_mem["c"])
    rule208=min(y_mem["D"], speed_mem["i"],dist_mem["b"])
    rule209=min(y_mem["D"], speed_mem["i"],dist_mem["a"])
    rule210=min(y_mem["E"], speed_mem["a"],dist_mem["f"])
    rule211=min(y_mem["E"], speed_mem["a"],dist_mem["f"])
    rule212=min(y_mem["E"], speed_mem["a"],dist_mem["e"])
    rule213=min(y_mem["E"], speed_mem["a"],dist_mem["d"])
    rule214=min(y_mem["E"], speed_mem["a"],dist_mem["c"])
    rule215=min(y_mem["E"], speed_mem["a"],dist_mem["b"])
    rule216=min(y_mem["E"], speed_mem["a"],dist_mem["a"])
    rule217=min(y_mem["E"], speed_mem["b"],dist_mem["f"])
    rule218=min(y_mem["E"], speed_mem["b"],dist_mem["f"])
    rule219=min(y_mem["E"], speed_mem["b"],dist_mem["e"])
    rule220=min(y_mem["E"], speed_mem["b"],dist_mem["d"])
    rule221=min(y_mem["E"], speed_mem["b"],dist_mem["c"])
    rule222=min(y_mem["E"], speed_mem["b"],dist_mem["b"])
    rule223=min(y_mem["E"], speed_mem["b"],dist_mem["a"])
    rule224=min(y_mem["E"], speed_mem["c"],dist_mem["f"])
    rule225=min(y_mem["E"], speed_mem["c"],dist_mem["f"])
    rule226=min(y_mem["E"], speed_mem["c"],dist_mem["e"])
    rule227=min(y_mem["E"], speed_mem["c"],dist_mem["d"])
    rule228=min(y_mem["E"], speed_mem["c"],dist_mem["c"])
    rule229=min(y_mem["E"], speed_mem["c"],dist_mem["b"])
    rule230=min(y_mem["E"], speed_mem["c"],dist_mem["a"])
    rule231=min(y_mem["E"], speed_mem["d"],dist_mem["f"])
    rule232=min(y_mem["E"], speed_mem["d"],dist_mem["f"])
    rule233=min(y_mem["E"], speed_mem["d"],dist_mem["e"])
    rule234=min(y_mem["E"], speed_mem["d"],dist_mem["d"])
    rule235=min(y_mem["E"], speed_mem["d"],dist_mem["c"])
    rule236=min(y_mem["E"], speed_mem["d"],dist_mem["b"])
    rule237=min(y_mem["E"], speed_mem["d"],dist_mem["a"])
    rule238=min(y_mem["E"], speed_mem["e"],dist_mem["f"])
    rule239=min(y_mem["E"], speed_mem["e"],dist_mem["f"])
    rule240=min(y_mem["E"], speed_mem["e"],dist_mem["e"])
    rule241=min(y_mem["E"], speed_mem["e"],dist_mem["d"])
    rule242=min(y_mem["E"], speed_mem["e"],dist_mem["c"])
    rule243=min(y_mem["E"], speed_mem["e"],dist_mem["b"])
    rule244=min(y_mem["E"], speed_mem["e"],dist_mem["a"])
    rule245=min(y_mem["E"], speed_mem["e"],dist_mem["f"])
    rule246=min(y_mem["E"], speed_mem["e"],dist_mem["f"])
    rule247=min(y_mem["E"], speed_mem["e"],dist_mem["e"])
    rule248=min(y_mem["E"], speed_mem["e"],dist_mem["d"])
    rule249=min(y_mem["E"], speed_mem["e"],dist_mem["c"])
    rule250=min(y_mem["E"], speed_mem["e"],dist_mem["b"])
    rule251=min(y_mem["E"], speed_mem["e"],dist_mem["a"])
    rule252=min(y_mem["E"], speed_mem["g"],dist_mem["f"])
    rule253=min(y_mem["E"], speed_mem["g"],dist_mem["f"])
    rule254=min(y_mem["E"], speed_mem["g"],dist_mem["e"])
    rule255=min(y_mem["E"], speed_mem["g"],dist_mem["d"])
    rule256=min(y_mem["E"], speed_mem["g"],dist_mem["c"])
    rule257=min(y_mem["E"], speed_mem["g"],dist_mem["b"])
    rule258=min(y_mem["E"], speed_mem["g"],dist_mem["a"])
    rule259=min(y_mem["E"], speed_mem["h"],dist_mem["f"])
    rule260=min(y_mem["E"], speed_mem["h"],dist_mem["f"])
    rule261=min(y_mem["E"], speed_mem["h"],dist_mem["e"])
    rule262=min(y_mem["E"], speed_mem["h"],dist_mem["d"])
    rule263=min(y_mem["E"], speed_mem["h"],dist_mem["c"])
    rule264=min(y_mem["E"], speed_mem["h"],dist_mem["b"])
    rule265=min(y_mem["E"], speed_mem["h"],dist_mem["a"])
    rule266=min(y_mem["E"], speed_mem["i"],dist_mem["f"])
    rule267=min(y_mem["E"], speed_mem["i"],dist_mem["f"])
    rule268=min(y_mem["E"], speed_mem["i"],dist_mem["e"])
    rule269=min(y_mem["E"], speed_mem["i"],dist_mem["d"])
    rule270=min(y_mem["E"], speed_mem["i"],dist_mem["c"])
    rule271=min(y_mem["E"], speed_mem["i"],dist_mem["b"])
    rule272=min(y_mem["E"], speed_mem["i"],dist_mem["a"])
    rule273=min(y_mem["E"], speed_mem["i"],dist_mem["f"])
    rule274=min(y_mem["E"], speed_mem["i"],dist_mem["f"])
    rule275=min(y_mem["E"], speed_mem["i"],dist_mem["e"])
    rule276=min(y_mem["E"], speed_mem["i"],dist_mem["d"])
    rule277=min(y_mem["E"], speed_mem["i"],dist_mem["c"])
    rule278=min(y_mem["E"], speed_mem["i"],dist_mem["b"])
    rule279=min(y_mem["E"], speed_mem["i"],dist_mem["a"])
    rule280=min(y_mem["F"], speed_mem["a"],dist_mem["f"])
    rule281=min(y_mem["F"], speed_mem["a"],dist_mem["f"])
    rule282=min(y_mem["F"], speed_mem["a"],dist_mem["e"])
    rule283=min(y_mem["F"], speed_mem["a"],dist_mem["d"])
    rule284=min(y_mem["F"], speed_mem["a"],dist_mem["c"])
    rule285=min(y_mem["F"], speed_mem["a"],dist_mem["b"])
    rule286=min(y_mem["F"], speed_mem["a"],dist_mem["a"])
    rule287=min(y_mem["F"], speed_mem["b"],dist_mem["f"])
    rule288=min(y_mem["F"], speed_mem["b"],dist_mem["f"])
    rule289=min(y_mem["F"], speed_mem["b"],dist_mem["e"])
    rule290=min(y_mem["F"], speed_mem["b"],dist_mem["d"])
    rule291=min(y_mem["F"], speed_mem["b"],dist_mem["c"])
    rule292=min(y_mem["F"], speed_mem["b"],dist_mem["b"])
    rule293=min(y_mem["F"], speed_mem["b"],dist_mem["a"])
    rule294=min(y_mem["F"], speed_mem["c"],dist_mem["f"])
    rule295=min(y_mem["F"], speed_mem["c"],dist_mem["f"])
    rule296=min(y_mem["F"], speed_mem["c"],dist_mem["e"])
    rule297=min(y_mem["F"], speed_mem["c"],dist_mem["d"])
    rule298=min(y_mem["F"], speed_mem["c"],dist_mem["c"])
    rule299=min(y_mem["F"], speed_mem["c"],dist_mem["b"])
    rule300=min(y_mem["F"], speed_mem["c"],dist_mem["a"])
    rule301=min(y_mem["F"], speed_mem["d"],dist_mem["f"])
    rule302=min(y_mem["F"], speed_mem["d"],dist_mem["f"])
    rule303=min(y_mem["F"], speed_mem["d"],dist_mem["e"])
    rule304=min(y_mem["F"], speed_mem["d"],dist_mem["d"])
    rule305=min(y_mem["F"], speed_mem["d"],dist_mem["c"])
    rule306=min(y_mem["F"], speed_mem["d"],dist_mem["b"])
    rule307=min(y_mem["F"], speed_mem["d"],dist_mem["a"])
    rule308=min(y_mem["F"], speed_mem["e"],dist_mem["f"])
    rule309=min(y_mem["F"], speed_mem["e"],dist_mem["f"])
    rule310=min(y_mem["F"], speed_mem["e"],dist_mem["e"])
    rule311=min(y_mem["F"], speed_mem["e"],dist_mem["d"])
    rule312=min(y_mem["F"], speed_mem["e"],dist_mem["c"])
    rule313=min(y_mem["F"], speed_mem["e"],dist_mem["b"])
    rule314=min(y_mem["F"], speed_mem["e"],dist_mem["a"])
    rule315=min(y_mem["F"], speed_mem["e"],dist_mem["f"])
    rule316=min(y_mem["F"], speed_mem["e"],dist_mem["f"])
    rule317=min(y_mem["F"], speed_mem["e"],dist_mem["e"])
    rule318=min(y_mem["F"], speed_mem["e"],dist_mem["d"])
    rule319=min(y_mem["F"], speed_mem["e"],dist_mem["c"])
    rule320=min(y_mem["F"], speed_mem["e"],dist_mem["b"])
    rule321=min(y_mem["F"], speed_mem["e"],dist_mem["a"])
    rule322=min(y_mem["F"], speed_mem["g"],dist_mem["f"])
    rule323=min(y_mem["F"], speed_mem["g"],dist_mem["f"])
    rule324=min(y_mem["F"], speed_mem["g"],dist_mem["e"])
    rule325=min(y_mem["F"], speed_mem["g"],dist_mem["d"])
    rule326=min(y_mem["F"], speed_mem["g"],dist_mem["c"])
    rule327=min(y_mem["F"], speed_mem["g"],dist_mem["b"])
    rule328=min(y_mem["F"], speed_mem["g"],dist_mem["a"])
    rule329=min(y_mem["F"], speed_mem["h"],dist_mem["f"])
    rule330=min(y_mem["F"], speed_mem["h"],dist_mem["f"])
    rule331=min(y_mem["F"], speed_mem["h"],dist_mem["e"])
    rule332=min(y_mem["F"], speed_mem["h"],dist_mem["d"])
    rule333=min(y_mem["F"], speed_mem["h"],dist_mem["c"])
    rule334=min(y_mem["F"], speed_mem["h"],dist_mem["b"])
    rule335=min(y_mem["F"], speed_mem["h"],dist_mem["a"])
    rule336=min(y_mem["F"], speed_mem["i"],dist_mem["f"])
    rule337=min(y_mem["F"], speed_mem["i"],dist_mem["f"])
    rule338=min(y_mem["F"], speed_mem["i"],dist_mem["e"])
    rule339=min(y_mem["F"], speed_mem["i"],dist_mem["d"])
    rule340=min(y_mem["F"], speed_mem["i"],dist_mem["c"])
    rule341=min(y_mem["F"], speed_mem["i"],dist_mem["b"])
    rule342=min(y_mem["F"], speed_mem["i"],dist_mem["a"])
    rule343=min(y_mem["F"], speed_mem["i"],dist_mem["f"])
    rule344=min(y_mem["F"], speed_mem["i"],dist_mem["f"])
    rule345=min(y_mem["F"], speed_mem["i"],dist_mem["e"])
    rule346=min(y_mem["F"], speed_mem["i"],dist_mem["d"])
    rule347=min(y_mem["F"], speed_mem["i"],dist_mem["c"])
    rule348=min(y_mem["F"], speed_mem["i"],dist_mem["b"])
    rule349=min(y_mem["F"], speed_mem["i"],dist_mem["a"])
    rule350=min(y_mem["G"], speed_mem["a"],dist_mem["f"])
    rule351=min(y_mem["G"], speed_mem["a"],dist_mem["f"])
    rule352=min(y_mem["G"], speed_mem["a"],dist_mem["e"])
    rule353=min(y_mem["G"], speed_mem["a"],dist_mem["d"])
    rule354=min(y_mem["G"], speed_mem["a"],dist_mem["c"])
    rule355=min(y_mem["G"], speed_mem["a"],dist_mem["b"])
    rule356=min(y_mem["G"], speed_mem["a"],dist_mem["a"])
    rule357=min(y_mem["G"], speed_mem["b"],dist_mem["f"])
    rule358=min(y_mem["G"], speed_mem["b"],dist_mem["f"])
    rule359=min(y_mem["G"], speed_mem["b"],dist_mem["e"])
    rule360=min(y_mem["G"], speed_mem["b"],dist_mem["d"])
    rule361=min(y_mem["G"], speed_mem["b"],dist_mem["c"])
    rule362=min(y_mem["G"], speed_mem["b"],dist_mem["b"])
    rule363=min(y_mem["G"], speed_mem["b"],dist_mem["a"])
    rule364=min(y_mem["G"], speed_mem["c"],dist_mem["f"])
    rule365=min(y_mem["G"], speed_mem["c"],dist_mem["f"])
    rule366=min(y_mem["G"], speed_mem["c"],dist_mem["e"])
    rule367=min(y_mem["G"], speed_mem["c"],dist_mem["d"])
    rule368=min(y_mem["G"], speed_mem["c"],dist_mem["c"])
    rule369=min(y_mem["G"], speed_mem["c"],dist_mem["b"])
    rule370=min(y_mem["G"], speed_mem["c"],dist_mem["a"])
    rule371=min(y_mem["G"], speed_mem["d"],dist_mem["f"])
    rule372=min(y_mem["G"], speed_mem["d"],dist_mem["f"])
    rule373=min(y_mem["G"], speed_mem["d"],dist_mem["e"])
    rule374=min(y_mem["G"], speed_mem["d"],dist_mem["d"])
    rule375=min(y_mem["G"], speed_mem["d"],dist_mem["c"])
    rule376=min(y_mem["G"], speed_mem["d"],dist_mem["b"])
    rule377=min(y_mem["G"], speed_mem["d"],dist_mem["a"])
    rule378=min(y_mem["G"], speed_mem["e"],dist_mem["f"])
    rule379=min(y_mem["G"], speed_mem["e"],dist_mem["f"])
    rule380=min(y_mem["G"], speed_mem["e"],dist_mem["e"])
    rule381=min(y_mem["G"], speed_mem["e"],dist_mem["d"])
    rule382=min(y_mem["G"], speed_mem["e"],dist_mem["c"])
    rule383=min(y_mem["G"], speed_mem["e"],dist_mem["b"])
    rule384=min(y_mem["G"], speed_mem["e"],dist_mem["a"])
    rule385=min(y_mem["G"], speed_mem["e"],dist_mem["f"])
    rule386=min(y_mem["G"], speed_mem["e"],dist_mem["f"])
    rule387=min(y_mem["G"], speed_mem["e"],dist_mem["e"])
    rule388=min(y_mem["G"], speed_mem["e"],dist_mem["d"])
    rule389=min(y_mem["G"], speed_mem["e"],dist_mem["c"])
    rule390=min(y_mem["G"], speed_mem["e"],dist_mem["b"])
    rule391=min(y_mem["G"], speed_mem["e"],dist_mem["a"])
    rule392=min(y_mem["G"], speed_mem["g"],dist_mem["f"])
    rule393=min(y_mem["G"], speed_mem["g"],dist_mem["f"])
    rule394=min(y_mem["G"], speed_mem["g"],dist_mem["e"])
    rule395=min(y_mem["G"], speed_mem["g"],dist_mem["d"])
    rule396=min(y_mem["G"], speed_mem["g"],dist_mem["c"])
    rule397=min(y_mem["G"], speed_mem["g"],dist_mem["b"])
    rule398=min(y_mem["G"], speed_mem["g"],dist_mem["a"])
    rule399=min(y_mem["G"], speed_mem["h"],dist_mem["f"])
    rule400=min(y_mem["G"], speed_mem["h"],dist_mem["f"])
    rule401=min(y_mem["G"], speed_mem["h"],dist_mem["e"])
    rule402=min(y_mem["G"], speed_mem["h"],dist_mem["d"])
    rule403=min(y_mem["G"], speed_mem["h"],dist_mem["c"])
    rule404=min(y_mem["G"], speed_mem["h"],dist_mem["b"])
    rule405=min(y_mem["G"], speed_mem["h"],dist_mem["a"])
    rule406=min(y_mem["G"], speed_mem["i"],dist_mem["f"])
    rule407=min(y_mem["G"], speed_mem["i"],dist_mem["f"])
    rule408=min(y_mem["G"], speed_mem["i"],dist_mem["e"])
    rule409=min(y_mem["G"], speed_mem["i"],dist_mem["d"])
    rule410=min(y_mem["G"], speed_mem["i"],dist_mem["c"])
    rule411=min(y_mem["G"], speed_mem["i"],dist_mem["b"])
    rule412=min(y_mem["G"], speed_mem["i"],dist_mem["a"])
    rule413=min(y_mem["G"], speed_mem["i"],dist_mem["f"])
    rule414=min(y_mem["G"], speed_mem["i"],dist_mem["f"])
    rule415=min(y_mem["G"], speed_mem["i"],dist_mem["e"])
    rule416=min(y_mem["G"], speed_mem["i"],dist_mem["d"])
    rule417=min(y_mem["G"], speed_mem["i"],dist_mem["c"])
    rule418=min(y_mem["G"], speed_mem["i"],dist_mem["b"])
    rule419=min(y_mem["G"], speed_mem["i"],dist_mem["a"])
    rule420=min(y_mem["H"], speed_mem["a"],dist_mem["f"])
    rule421=min(y_mem["H"], speed_mem["a"],dist_mem["f"])
    rule422=min(y_mem["H"], speed_mem["a"],dist_mem["e"])
    rule423=min(y_mem["H"], speed_mem["a"],dist_mem["d"])
    rule424=min(y_mem["H"], speed_mem["a"],dist_mem["c"])
    rule425=min(y_mem["H"], speed_mem["a"],dist_mem["b"])
    rule426=min(y_mem["H"], speed_mem["a"],dist_mem["a"])
    rule427=min(y_mem["H"], speed_mem["b"],dist_mem["f"])
    rule428=min(y_mem["H"], speed_mem["b"],dist_mem["f"])
    rule429=min(y_mem["H"], speed_mem["b"],dist_mem["e"])
    rule430=min(y_mem["H"], speed_mem["b"],dist_mem["d"])
    rule431=min(y_mem["H"], speed_mem["b"],dist_mem["c"])
    rule432=min(y_mem["H"], speed_mem["b"],dist_mem["b"])
    rule433=min(y_mem["H"], speed_mem["b"],dist_mem["a"])
    rule434=min(y_mem["H"], speed_mem["c"],dist_mem["f"])
    rule435=min(y_mem["H"], speed_mem["c"],dist_mem["f"])
    rule436=min(y_mem["H"], speed_mem["c"],dist_mem["e"])
    rule437=min(y_mem["H"], speed_mem["c"],dist_mem["d"])
    rule438=min(y_mem["H"], speed_mem["c"],dist_mem["c"])
    rule439=min(y_mem["H"], speed_mem["c"],dist_mem["b"])
    rule440=min(y_mem["H"], speed_mem["c"],dist_mem["a"])
    rule441=min(y_mem["H"], speed_mem["d"],dist_mem["f"])
    rule442=min(y_mem["H"], speed_mem["d"],dist_mem["f"])
    rule443=min(y_mem["H"], speed_mem["d"],dist_mem["e"])
    rule444=min(y_mem["H"], speed_mem["d"],dist_mem["d"])
    rule445=min(y_mem["H"], speed_mem["d"],dist_mem["c"])
    rule446=min(y_mem["H"], speed_mem["d"],dist_mem["b"])
    rule447=min(y_mem["H"], speed_mem["d"],dist_mem["a"])
    rule448=min(y_mem["H"], speed_mem["e"],dist_mem["f"])
    rule449=min(y_mem["H"], speed_mem["e"],dist_mem["f"])
    rule450=min(y_mem["H"], speed_mem["e"],dist_mem["e"])
    rule451=min(y_mem["H"], speed_mem["e"],dist_mem["d"])
    rule452=min(y_mem["H"], speed_mem["e"],dist_mem["c"])
    rule453=min(y_mem["H"], speed_mem["e"],dist_mem["b"])
    rule454=min(y_mem["H"], speed_mem["e"],dist_mem["a"])
    rule455=min(y_mem["H"], speed_mem["e"],dist_mem["f"])
    rule456=min(y_mem["H"], speed_mem["e"],dist_mem["f"])
    rule457=min(y_mem["H"], speed_mem["e"],dist_mem["e"])
    rule458=min(y_mem["H"], speed_mem["e"],dist_mem["d"])
    rule459=min(y_mem["H"], speed_mem["e"],dist_mem["c"])
    rule460=min(y_mem["H"], speed_mem["e"],dist_mem["b"])
    rule461=min(y_mem["H"], speed_mem["e"],dist_mem["a"])
    rule462=min(y_mem["H"], speed_mem["g"],dist_mem["f"])
    rule463=min(y_mem["H"], speed_mem["g"],dist_mem["f"])
    rule464=min(y_mem["H"], speed_mem["g"],dist_mem["e"])
    rule465=min(y_mem["H"], speed_mem["g"],dist_mem["d"])
    rule466=min(y_mem["H"], speed_mem["g"],dist_mem["c"])
    rule467=min(y_mem["H"], speed_mem["g"],dist_mem["b"])
    rule468=min(y_mem["H"], speed_mem["g"],dist_mem["a"])
    rule469=min(y_mem["H"], speed_mem["h"],dist_mem["f"])
    rule470=min(y_mem["H"], speed_mem["h"],dist_mem["f"])
    rule471=min(y_mem["H"], speed_mem["h"],dist_mem["e"])
    rule472=min(y_mem["H"], speed_mem["h"],dist_mem["d"])
    rule473=min(y_mem["H"], speed_mem["h"],dist_mem["c"])
    rule474=min(y_mem["H"], speed_mem["h"],dist_mem["b"])
    rule475=min(y_mem["H"], speed_mem["h"],dist_mem["a"])
    rule476=min(y_mem["H"], speed_mem["i"],dist_mem["f"])
    rule477=min(y_mem["H"], speed_mem["i"],dist_mem["f"])
    rule478=min(y_mem["H"], speed_mem["i"],dist_mem["e"])
    rule479=min(y_mem["H"], speed_mem["i"],dist_mem["d"])
    rule480=min(y_mem["H"], speed_mem["i"],dist_mem["c"])
    rule481=min(y_mem["H"], speed_mem["i"],dist_mem["b"])
    rule482=min(y_mem["H"], speed_mem["i"],dist_mem["a"])
    rule483=min(y_mem["H"], speed_mem["i"],dist_mem["f"])
    rule484=min(y_mem["H"], speed_mem["i"],dist_mem["f"])
    rule485=min(y_mem["H"], speed_mem["i"],dist_mem["e"])
    rule486=min(y_mem["H"], speed_mem["i"],dist_mem["d"])
    rule487=min(y_mem["H"], speed_mem["i"],dist_mem["c"])
    rule488=min(y_mem["H"], speed_mem["i"],dist_mem["b"])
    rule489=min(y_mem["H"], speed_mem["i"],dist_mem["a"])
    rule490=min(y_mem["I"], speed_mem["a"],dist_mem["f"])
    rule491=min(y_mem["I"], speed_mem["a"],dist_mem["f"])
    rule492=min(y_mem["I"], speed_mem["a"],dist_mem["e"])
    rule493=min(y_mem["I"], speed_mem["a"],dist_mem["d"])
    rule494=min(y_mem["I"], speed_mem["a"],dist_mem["c"])
    rule495=min(y_mem["I"], speed_mem["a"],dist_mem["b"])
    rule496=min(y_mem["I"], speed_mem["a"],dist_mem["a"])
    rule497=min(y_mem["I"], speed_mem["b"],dist_mem["f"])
    rule498=min(y_mem["I"], speed_mem["b"],dist_mem["f"])
    rule499=min(y_mem["I"], speed_mem["b"],dist_mem["e"])
    rule500=min(y_mem["I"], speed_mem["b"],dist_mem["d"])
    rule501=min(y_mem["I"], speed_mem["b"],dist_mem["c"])
    rule502=min(y_mem["I"], speed_mem["b"],dist_mem["b"])
    rule503=min(y_mem["I"], speed_mem["b"],dist_mem["a"])
    rule504=min(y_mem["I"], speed_mem["c"],dist_mem["f"])
    rule505=min(y_mem["I"], speed_mem["c"],dist_mem["f"])
    rule506=min(y_mem["I"], speed_mem["c"],dist_mem["e"])
    rule507=min(y_mem["I"], speed_mem["c"],dist_mem["d"])
    rule508=min(y_mem["I"], speed_mem["c"],dist_mem["c"])
    rule509=min(y_mem["I"], speed_mem["c"],dist_mem["b"])
    rule510=min(y_mem["I"], speed_mem["c"],dist_mem["a"])
    rule511=min(y_mem["I"], speed_mem["d"],dist_mem["f"])
    rule512=min(y_mem["I"], speed_mem["d"],dist_mem["f"])
    rule513=min(y_mem["I"], speed_mem["d"],dist_mem["e"])
    rule514=min(y_mem["I"], speed_mem["d"],dist_mem["d"])
    rule515=min(y_mem["I"], speed_mem["d"],dist_mem["c"])
    rule516=min(y_mem["I"], speed_mem["d"],dist_mem["b"])
    rule517=min(y_mem["I"], speed_mem["d"],dist_mem["a"])
    rule518=min(y_mem["I"], speed_mem["e"],dist_mem["f"])
    rule519=min(y_mem["I"], speed_mem["e"],dist_mem["f"])
    rule520=min(y_mem["I"], speed_mem["e"],dist_mem["e"])
    rule521=min(y_mem["I"], speed_mem["e"],dist_mem["d"])
    rule522=min(y_mem["I"], speed_mem["e"],dist_mem["c"])
    rule523=min(y_mem["I"], speed_mem["e"],dist_mem["b"])
    rule524=min(y_mem["I"], speed_mem["e"],dist_mem["a"])
    rule525=min(y_mem["I"], speed_mem["e"],dist_mem["f"])
    rule526=min(y_mem["I"], speed_mem["e"],dist_mem["f"])
    rule527=min(y_mem["I"], speed_mem["e"],dist_mem["e"])
    rule528=min(y_mem["I"], speed_mem["e"],dist_mem["d"])
    rule529=min(y_mem["I"], speed_mem["e"],dist_mem["c"])
    rule530=min(y_mem["I"], speed_mem["e"],dist_mem["b"])
    rule531=min(y_mem["I"], speed_mem["e"],dist_mem["a"])
    rule532=min(y_mem["I"], speed_mem["g"],dist_mem["f"])
    rule533=min(y_mem["I"], speed_mem["g"],dist_mem["f"])
    rule534=min(y_mem["I"], speed_mem["g"],dist_mem["e"])
    rule535=min(y_mem["I"], speed_mem["g"],dist_mem["d"])
    rule536=min(y_mem["I"], speed_mem["g"],dist_mem["c"])
    rule537=min(y_mem["I"], speed_mem["g"],dist_mem["b"])
    rule538=min(y_mem["I"], speed_mem["g"],dist_mem["a"])
    rule539=min(y_mem["I"], speed_mem["h"],dist_mem["f"])
    rule540=min(y_mem["I"], speed_mem["h"],dist_mem["f"])
    rule541=min(y_mem["I"], speed_mem["h"],dist_mem["e"])
    rule542=min(y_mem["I"], speed_mem["h"],dist_mem["d"])
    rule543=min(y_mem["I"], speed_mem["h"],dist_mem["c"])
    rule544=min(y_mem["I"], speed_mem["h"],dist_mem["b"])
    rule545=min(y_mem["I"], speed_mem["h"],dist_mem["a"])
    rule546=min(y_mem["I"], speed_mem["i"],dist_mem["f"])
    rule547=min(y_mem["I"], speed_mem["i"],dist_mem["f"])
    rule548=min(y_mem["I"], speed_mem["i"],dist_mem["e"])
    rule549=min(y_mem["I"], speed_mem["i"],dist_mem["d"])
    rule550=min(y_mem["I"], speed_mem["i"],dist_mem["c"])
    rule551=min(y_mem["I"], speed_mem["i"],dist_mem["b"])
    rule552=min(y_mem["I"], speed_mem["i"],dist_mem["a"])
    rule553=min(y_mem["I"], speed_mem["i"],dist_mem["f"])
    rule554=min(y_mem["I"], speed_mem["i"],dist_mem["f"])
    rule555=min(y_mem["I"], speed_mem["i"],dist_mem["e"])
    rule556=min(y_mem["I"], speed_mem["i"],dist_mem["d"])
    rule557=min(y_mem["I"], speed_mem["i"],dist_mem["c"])
    rule558=min(y_mem["I"], speed_mem["i"],dist_mem["b"])
    rule559=min(y_mem["I"], speed_mem["i"],dist_mem["a"])
    rule560=min(y_mem["J"], speed_mem["a"],dist_mem["f"])
    rule561=min(y_mem["J"], speed_mem["a"],dist_mem["f"])
    rule562=min(y_mem["J"], speed_mem["a"],dist_mem["e"])
    rule563=min(y_mem["J"], speed_mem["a"],dist_mem["d"])
    rule564=min(y_mem["J"], speed_mem["a"],dist_mem["c"])
    rule565=min(y_mem["J"], speed_mem["a"],dist_mem["b"])
    rule566=min(y_mem["J"], speed_mem["a"],dist_mem["a"])
    rule567=min(y_mem["J"], speed_mem["b"],dist_mem["f"])
    rule568=min(y_mem["J"], speed_mem["b"],dist_mem["f"])
    rule569=min(y_mem["J"], speed_mem["b"],dist_mem["e"])
    rule570=min(y_mem["J"], speed_mem["b"],dist_mem["d"])
    rule571=min(y_mem["J"], speed_mem["b"],dist_mem["c"])
    rule572=min(y_mem["J"], speed_mem["b"],dist_mem["b"])
    rule573=min(y_mem["J"], speed_mem["b"],dist_mem["a"])
    rule574=min(y_mem["J"], speed_mem["c"],dist_mem["f"])
    rule575=min(y_mem["J"], speed_mem["c"],dist_mem["f"])
    rule576=min(y_mem["J"], speed_mem["c"],dist_mem["e"])
    rule577=min(y_mem["J"], speed_mem["c"],dist_mem["d"])
    rule578=min(y_mem["J"], speed_mem["c"],dist_mem["c"])
    rule579=min(y_mem["J"], speed_mem["c"],dist_mem["b"])
    rule580=min(y_mem["J"], speed_mem["c"],dist_mem["a"])
    rule581=min(y_mem["J"], speed_mem["d"],dist_mem["f"])
    rule582=min(y_mem["J"], speed_mem["d"],dist_mem["f"])
    rule583=min(y_mem["J"], speed_mem["d"],dist_mem["e"])
    rule584=min(y_mem["J"], speed_mem["d"],dist_mem["d"])
    rule585=min(y_mem["J"], speed_mem["d"],dist_mem["c"])
    rule586=min(y_mem["J"], speed_mem["d"],dist_mem["b"])
    rule587=min(y_mem["J"], speed_mem["d"],dist_mem["a"])
    rule588=min(y_mem["J"], speed_mem["e"],dist_mem["f"])
    rule589=min(y_mem["J"], speed_mem["e"],dist_mem["f"])
    rule590=min(y_mem["J"], speed_mem["e"],dist_mem["e"])
    rule591=min(y_mem["J"], speed_mem["e"],dist_mem["d"])
    rule592=min(y_mem["J"], speed_mem["e"],dist_mem["c"])
    rule593=min(y_mem["J"], speed_mem["e"],dist_mem["b"])
    rule594=min(y_mem["J"], speed_mem["e"],dist_mem["a"])
    rule595=min(y_mem["J"], speed_mem["e"],dist_mem["f"])
    rule596=min(y_mem["J"], speed_mem["e"],dist_mem["f"])
    rule597=min(y_mem["J"], speed_mem["e"],dist_mem["e"])
    rule598=min(y_mem["J"], speed_mem["e"],dist_mem["d"])
    rule599=min(y_mem["J"], speed_mem["e"],dist_mem["c"])
    rule600=min(y_mem["J"], speed_mem["e"],dist_mem["b"])
    rule601=min(y_mem["J"], speed_mem["e"],dist_mem["a"])
    rule602=min(y_mem["J"], speed_mem["g"],dist_mem["f"])
    rule603=min(y_mem["J"], speed_mem["g"],dist_mem["f"])
    rule604=min(y_mem["J"], speed_mem["g"],dist_mem["e"])
    rule605=min(y_mem["J"], speed_mem["g"],dist_mem["d"])
    rule606=min(y_mem["J"], speed_mem["g"],dist_mem["c"])
    rule607=min(y_mem["J"], speed_mem["g"],dist_mem["b"])
    rule608=min(y_mem["J"], speed_mem["g"],dist_mem["a"])
    rule609=min(y_mem["J"], speed_mem["h"],dist_mem["f"])
    rule610=min(y_mem["J"], speed_mem["h"],dist_mem["f"])
    rule611=min(y_mem["J"], speed_mem["h"],dist_mem["e"])
    rule612=min(y_mem["J"], speed_mem["h"],dist_mem["d"])
    rule613=min(y_mem["J"], speed_mem["h"],dist_mem["c"])
    rule614=min(y_mem["J"], speed_mem["h"],dist_mem["b"])
    rule615=min(y_mem["J"], speed_mem["h"],dist_mem["a"])
    rule616=min(y_mem["J"], speed_mem["i"],dist_mem["f"])
    rule617=min(y_mem["J"], speed_mem["i"],dist_mem["f"])
    rule618=min(y_mem["J"], speed_mem["i"],dist_mem["e"])
    rule619=min(y_mem["J"], speed_mem["i"],dist_mem["d"])
    rule620=min(y_mem["J"], speed_mem["i"],dist_mem["c"])
    rule621=min(y_mem["J"], speed_mem["i"],dist_mem["b"])
    rule622=min(y_mem["J"], speed_mem["i"],dist_mem["a"])
    rule623=min(y_mem["J"], speed_mem["i"],dist_mem["f"])
    rule624=min(y_mem["J"], speed_mem["i"],dist_mem["f"])
    rule625=min(y_mem["J"], speed_mem["i"],dist_mem["e"])
    rule626=min(y_mem["J"], speed_mem["i"],dist_mem["d"])
    rule627=min(y_mem["J"], speed_mem["i"],dist_mem["c"])
    rule628=min(y_mem["J"], speed_mem["i"],dist_mem["b"])
    rule629=min(y_mem["J"], speed_mem["i"],dist_mem["a"])
    
    A= rule196
    B= max(rule1, rule6, rule13, rule20, rule26, rule27, rule30, rule31, rule32, rule33, rule34, rule38, rule39, rule40, rule41, rule47, rule48, rule55, rule62, rule64, rule69, rule70, rule76, rule83, rule89, rule90, rule95, rule96, rule97, rule98, rule99, rule100, rule101, rule102, rule103, rule104, rule126, rule140, rule145, rule152, rule159, rule164, rule165, rule168, rule169, rule215, rule222, rule228, rule233, rule234, rule267, rule275, rule298, rule302, rule303, rule337, rule345, rule361, rule367, rule371, rule372, rule424, rule431, rule437, rule441, rule478, rule494, rule506, rule539, rule548, rule556, rule570, rule576, rule609, rule610, rule626)
    C= max(rule0, rule19, rule25, rule28, rule29, rule35, rule36, rule37, rule46, rule54, rule56, rule71, rule75, rule82, rule94, rule107, rule108, rule109, rule110, rule111, rule117, rule118, rule125, rule132, rule134, rule139, rule146, rule153, rule158, rule160, rule163, rule166, rule167, rule170, rule171, rule172, rule173, rule174, rule197, rule205, rule210, rule229, rule232, rule235, rule238, rule239, rule266, rule285, rule291, rule292, rule297, rule301, rule304, rule336, rule354, rule368, rule373, rule407, rule408, rule415, rule436, rule442, rule469, rule486, rule500, rule501, rule507, rule511, rule540, rule564, rule575, rule618, rule619)
    D= max(rule5, rule7, rule12, rule24, rule45, rule61, rule63, rule88, rule93, rule105, rule106, rule116, rule124, rule127, rule133, rule135, rule141, rule162, rule177, rule178, rule179, rule180, rule181, rule187, rule188, rule195, rule202, rule204, rule209, rule216, rule221, rule223, rule227, rule230, rule231, rule236, rule237, rule240, rule241, rule242, rule243, rule244, rule280, rule284, rule299, rule305, rule308, rule309, rule338, rule355, rule362, rule366, rule374, rule399, rule406, rule416, rule430, rule438, rule443, rule470, rule477, rule485, rule505, rule512, rule549, rule563, rule571, rule574, rule577, rule581, rule611)
    E= max(rule2, rule8, rule18, rule23, rule44, rule53, rule57, rule65, rule68, rule77, rule92, rule115, rule131, rule151, rule157, rule161, rule175, rule176, rule186, rule194, rule203, rule211, rule214, rule247, rule248, rule249, rule250, rule251, rule257, rule258, rule265, rule268, rule272, rule274, rule279, rule286, rule293, rule296, rule300, rule306, rule307, rule310, rule311, rule312, rule313, rule314, rule329, rule346, rule350, rule360, rule369, rule375, rule378, rule379, rule400, rule425, rule432, rule435, rule444, rule479, rule493, rule504, rule508, rule513, rule541, rule547, rule555, rule569, rule582, rule627)
    F= max(rule22, rule43, rule72, rule78, rule81, rule87, rule91, rule114, rule123, rule138, rule144, rule147, rule185, rule198, rule201, rule217, rule226, rule245, rule246, rule256, rule259, rule264, rule273, rule276, rule281, rule290, rule317, rule318, rule319, rule320, rule321, rule327, rule328, rule330, rule335, rule342, rule344, rule349, rule356, rule363, rule365, rule370, rule376, rule377, rule380, rule381, rule382, rule383, rule384, rule409, rule420, rule423, rule434, rule439, rule445, rule448, rule449, rule471, rule476, rule495, rule499, rule502, rule514, rule546, rule557, rule578, rule583, rule602, rule603, rule612, rule617, rule620, rule625)
    G= max(rule11, rule17, rule21, rule42, rule52, rule60, rule74, rule113, rule128, rule142, rule148, rule156, rule184, rule189, rule193, rule206, rule208, rule220, rule255, rule260, rule271, rule295, rule315, rule316, rule326, rule334, rule339, rule343, rule351, rule353, rule364, rule387, rule388, rule389, rule390, rule391, rule397, rule398, rule401, rule405, rule412, rule414, rule419, rule426, rule429, rule433, rule440, rule446, rule447, rule450, rule451, rule452, rule453, rule454, rule487, rule490, rule509, rule515, rule518, rule519, rule532, rule533, rule542, rule550, rule565, rule572, rule584, rule604, rule616)
    H= max(rule4, rule9, rule58, rule67, rule86, rule112, rule119, rule122, rule130, rule136, rule150, rule183, rule190, rule212, rule218, rule225, rule254, rule263, rule269, rule278, rule283, rule287, rule294, rule325, rule331, rule341, rule359, rule385, rule386, rule396, rule404, rule413, rule417, rule421, rule457, rule458, rule459, rule460, rule461, rule462, rule463, rule467, rule468, rule472, rule475, rule480, rule482, rule484, rule489, rule496, rule503, rule510, rule516, rule517, rule520, rule521, rule522, rule523, rule524, rule534, rule560, rule562, rule568, rule579, rule585, rule588, rule589, rule605, rule613, rule628)
    I= max(rule3, rule14, rule16, rule49, rule51, rule66, rule79, rule80, rule120, rule137, rule155, rule182, rule192, rule199, rule200, rule213, rule224, rule253, rule261, rule282, rule288, rule289, rule324, rule333, rule347, rule348, rule357, rule392, rule393, rule395, rule402, rule410, rule411, rule427, rule455, rule456, rule464, rule466, rule474, rule483, rule491, rule492, rule498, rule527, rule528, rule529, rule530, rule531, rule535, rule537, rule538, rule543, rule545, rule552, rule554, rule558, rule559, rule566, rule567, rule573, rule580, rule586, rule587, rule590, rule591, rule592, rule593, rule594, rule606, rule621, rule623)
    J= max(rule10, rule15, rule50, rule59, rule73, rule84, rule85, rule121, rule129, rule143, rule149, rule154, rule191, rule207, rule219, rule252, rule262, rule270, rule277, rule322, rule323, rule332, rule340, rule352, rule358, rule394, rule403, rule418, rule422, rule428, rule465, rule473, rule481, rule488, rule497, rule525, rule526, rule536, rule544, rule551, rule553, rule561, rule595, rule596, rule597, rule598, rule599, rule600, rule601, rule607, rule608, rule614, rule615, rule622, rule624, rule629)
    

    return A,B,C,D,E,F,G,H,I,J

# and calculate the COG
def defuzzificationAssessment(A, B, C, D, E, F, G, H, I, J):
    numerator = 0
    denominator = 0
    for i in range(500):
        op = getMembershipYPos(i)
        tt = max(min(op["A"], A), min(op["B"], B), min(op["C"], C),min(op["D"], D),min(op["E"], E),min(op["F"], F),min(op["G"], G),min(op["H"], H),min(op["I"], I),min(op["J"], J))  # Same logic for other fuzzy sets
        if tt > 0:  # Consider only non-zero memberships
            numerator += i * tt
            denominator += tt
    if denominator == 0:
        return None  # Handle cases where no fuzzy set applies
    cog = numerator / denominator
    return cog


# Predict the y position based on fuzzy inference and defuzzification
def predictYPosition(y, speed,pos):
    A,B,C,D,E,F,G,H,I,J = fuzzyInference(y, speed,pos)
    return defuzzificationAssessment(A,B,C,D,E,F,G,H,I,J)

# Example predictions with the enhanced system
sample_data = [
    (450, -4 ,550 ,504), (50 ,6 ,400 ,322), (200, 0.5, 550, 316.5), (300, -7.5 ,400 ,462.5), (200, 2, 200 ,340),
    (400, 6, 400, 120), (100, 0.5 ,300, 185.0), (250 ,-4,300 ,76), (300, 0.5 ,300 ,385.0), (150, 4, 100 ,280)
]

predictions = []
for y, speed, pos, predicted_y in sample_data:
    predictions.append(predictYPosition(y, speed,pos))

print("Predicted Y Positions:", predictions)

# Validate predictions against actual data
actual_data = [predicted_y for _, _, _, predicted_y in sample_data]
for pred, actual in zip(predictions, actual_data):
    print(f"Predicted: {pred:.2f}, Actual: {actual}")
